# Generated by Django 4.1.4 on 2023-01-14 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_user_diagnosis_alter_user_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
    ]
