# Generated by Django 4.1.4 on 2023-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='m', max_length=1),
            preserve_default=False,
        ),
    ]
